version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "
    env_file:
      - .env
    volumes:
      - static_volume:/app/apps/static
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16.4
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

volumes:
  postgres_data:
  static_volume:
