# Generated by Django 5.1.8 on 2025-07-08 19:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('codigo', models.IntegerField(help_text='Código único do cargo', primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(help_text='Nome do cargo', max_length=100)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nome'],
            },
        ),
    ]
