# Generated by Django 5.1.8 on 2025-07-08 19:54

import uuid
from django.db import migrations
 
 
def populate_cargos(apps, schema_editor):
    """
    Popula a tabela de cargos com dados iniciais
    """
 
    cargo = apps.get_model('users', 'Cargo')
 
    # Lista de cargos iniciais
    cargos_iniciais = [
        {
            'codigo': 3085,
            'nome': 'ASSISTENTE DE DIRETOR DE ESCOLA',
            'uuid': uuid.uuid4()
        }
    ]
 
    for cargo_data in cargos_iniciais:
        cargo.objects.get_or_create(
            codigo=cargo_data['codigo'],
            defaults={
                'nome': cargo_data['nome'],
                'uuid': cargo_data['uuid']
            }
        )
 
def reverse_populate_cargos(apps, schema_editor):
    """
    Função para reverter a migração (remover os cargos)
    """
    cargo = apps.get_model('users', 'Cargo')
    # Códigos dos cargos a serem removidos
    codigos_para_remover = [3085]
    cargo.objects.filter(codigo__in=codigos_para_remover).delete()
 
 
class Migration(migrations.Migration):
 
    dependencies = [
        ('users', '0002_cargo'),
    ]
 
    operations = [
        migrations.RunPython(
            populate_cargos,
            reverse_populate_cargos,
        ),
    ]