# Generated by Django 5.1.8 on 2025-07-08 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_popula_cargos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.ForeignKey(default=3085, help_text='Cargo do usuário no sistema', on_delete=django.db.models.deletion.PROTECT, to='users.cargo'),
        ),
    ]
