# Generated by Django 5.1.8 on 2025-07-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_cargo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cargo",
            options={
                "ordering": ["nome"],
                "verbose_name": "Perfil de Acesso",
                "verbose_name_plural": "Perfis de Acesso",
            },
        ),
        migrations.AlterField(
            model_name="cargo",
            name="nome",
            field=models.CharField(help_text="Perfil de acesso", max_length=100),
        ),
    ]
