# Generated by Django 5.1.8 on 2025-07-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
        ('users', '0005_alter_cargo_options_alter_cargo_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rede',
            field=models.CharField(choices=[('DIRETA', 'Direta'), ('INDIRETA', 'Indireta ou parceira')], default='DIRETA', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='unidades',
            field=models.ManyToManyField(blank=True, help_text='Unidades associadas ao usuário', related_name='usuarios', to='unidades.unidade'),
        ),
    ]
