# Generated by Django 5.1.8 on 2025-08-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_rede_user_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_validado',
            field=models.BooleanField(default=False, help_text='Indica se o usuário foi validado', verbose_name='Validado'),
        ),
    ]
