# Generated by Django 5.1.8 on 2025-08-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_validado'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_core_sso',
            field=models.BooleanField(default=False, help_text='Indica se o usuário possue cadastro no coreSSO', verbose_name='CoreSSO'),
        ),
    ]
