# Generated by Django 5.1.8 on 2025-12-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_core_sso'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_app_admin',
            field=models.BooleanField(default=False, help_text='Indica se o usuário é administrador funcional do GIPE', verbose_name='Administrador GIPE'),
        ),
    ]
