# Generated by Django 5.1.8 on 2025-12-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_app_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o usuário foi aprovado', null=True, verbose_name='Data de Aprovação'),
        ),
        migrations.AddField(
            model_name='user',
            name='responsavel_aprovacao',
            field=models.CharField(blank=True, help_text='Codigo responsável pela aprovação', max_length=11, null=True, verbose_name='Responsável pela Aprovação'),
        ),
    ]
