# Generated by Django 5.1.8 on 2025-12-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_data_aprovacao_user_responsavel_aprovacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_inativacao',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o usuário foi inativado', null=True, verbose_name='Data de Inativação'),
        ),
        migrations.AddField(
            model_name='user',
            name='responsavel_inativacao',
            field=models.CharField(blank=True, help_text='Codigo responsável pela inativação', max_length=11, null=True, verbose_name='Responsável pela Inativação'),
        ),
    ]
