# Generated by Django 5.1.8 on 2026-01-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_data_inativacao_user_responsavel_inativacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inativado_via_unidade',
            field=models.BooleanField(default=False, help_text='Indica se o usuário foi inativado através da unidade', verbose_name='Inativado via unidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='motivo_inativacao',
            field=models.TextField(blank=True, help_text='Descrição do motivo da inativação do usuário.', verbose_name='Motivo Inativação'),
        ),
    ]
