# Generated by Django 5.1.8 on 2025-07-22 18:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('nome', models.CharField(max_length=160, verbose_name='Nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_unidade', models.CharField(choices=[('ADM', 'ADM'), ('DRE', 'DRE'), ('IFSP', 'IFSP'), ('CMCT', 'CMCT'), ('CECI', 'CECI'), ('CEI', 'CEI'), ('CEMEI', 'CEMEI'), ('CIEJA', 'CIEJA'), ('EMEBS', 'EMEBS'), ('EMEF', 'EMEF'), ('EMEFM', 'EMEFM'), ('EMEI', 'EMEI'), ('CEU', 'CEU'), ('CEU CEI', 'CEU CEI'), ('CEU EMEF', 'CEU EMEF'), ('CEU EMEI', 'CEU EMEI'), ('CEU CEMEI', 'CEU CEMEI'), ('CEI DIRET', 'CEI DIRET')], default='ADM', max_length=10)),
                ('rede', models.CharField(choices=[('DIRETA', 'Direta'), ('INDIRETA', 'Indireta ou parceira')], default='DIRETA', max_length=10)),
                ('codigo_eol', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('sigla', models.CharField(blank=True, default='', max_length=4)),
                ('dre', models.ForeignKey(blank=True, limit_choices_to={'tipo_unidade': 'DRE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades_da_dre', to='unidades.unidade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
