# Generated by Django 5.1.8 on 2025-12-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='ativa',
            field=models.BooleanField(default=True, help_text='Indica se a unidade está ativa ou inativa.', verbose_name='Ativa'),
        ),
    ]
