# Generated by Django 5.1.8 on 2026-01-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_unidade_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='data_inativacao',
            field=models.DateTimeField(blank=True, help_text='Data e hora que a unidade foi inativada', null=True, verbose_name='Data de Inativação'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='motivo_inativacao',
            field=models.TextField(blank=True, help_text='Descrição do motivo da inativação da unidade.', verbose_name='Motivo Inativação'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='responsavel_inativacao',
            field=models.CharField(blank=True, help_text='Codigo responsável pela inativação', max_length=11, verbose_name='Responsável pela Inativação'),
        ),
    ]
