# Generated by Django 5.1.8 on 2026-01-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0003_unidade_data_inativacao_unidade_motivo_inativacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='data_reativacao',
            field=models.DateTimeField(blank=True, help_text='Data e hora que a unidade foi reativada', null=True, verbose_name='Data da reativacao'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='motivo_reativacao',
            field=models.TextField(blank=True, help_text='Descrição do motivo da reativação da unidade.', verbose_name='Motivo Reativação'),
        ),
        migrations.AddField(
            model_name='unidade',
            name='responsavel_reativacao',
            field=models.CharField(blank=True, help_text='Codigo do responsável pela reativacao', max_length=11, verbose_name='Responsável pela Reativação'),
        ),
    ]
