# Generated by Django 5.1.8 on 2026-04-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0004_unidade_data_reativacao_unidade_motivo_reativacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='tipo_unidade',
            field=models.CharField(choices=[('ADM', 'ADM'), ('DRE', 'DRE'), ('IFSP', 'IFSP'), ('CMCT', 'CMCT'), ('CECI', 'CECI'), ('CEI', 'CEI'), ('CEMEI', 'CEMEI'), ('CIEJA', 'CIEJA'), ('EMEBS', 'EMEBS'), ('EMEF', 'EMEF'), ('EMEFM', 'EMEFM'), ('EMEI', 'EMEI'), ('CEU', 'CEU'), ('CEU CEI', 'CEU CEI'), ('CEU EMEF', 'CEU EMEF'), ('CEU EMEI', 'CEU EMEI'), ('CEU CEMEI', 'CEU CEMEI'), ('CEI DIRET', 'CEI DIRET'), ('EMEI P FOM', 'EMEI P FOM'), ('EMEF P FOM', 'EMEF P FOM'), ('CR.P.CONV', 'CR.P.CONV'), ('CEI INDIR', 'CEI INDIR'), ('CCI/CIPS', 'CCI/CIPS'), ('MOVA', 'MOVA'), ('ESP CONV', 'ESP CONV'), ('CEU AT COM', 'CEU AT COM'), ('CEU POLO', 'CEU POLO')], default='ADM', max_length=10),
        ),
    ]
